steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_API_URL=${_BACKEND_URL}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/quantum-frontend:latest'
      - '.'
images:
  - 'gcr.io/$PROJECT_ID/quantum-frontend:latest'



