/**
 * Client-side simulator for the trained 14-qubit variational quantum classifier.
 *
 * Mirrors the PennyLane circuit the backend ran:
 *   AngleEmbedding(x * pi, rotation='Y') -> StronglyEntanglingLayers(w) -> <Z_0>
 *
 * Wire 0 is the most significant bit of the state-vector index, matching
 * PennyLane's default.qubit. Verified against the Python implementation to
 * ~1e-15 across the fixture in quantum.test.js; if you change anything here,
 * re-run that test.
 */

export const N_QUBITS = 14;
const DIM = 1 << N_QUBITS;

/** Apply a real-valued 2x2 [[a,b],[c,d]] to `wire`. */
function applyReal2x2(re, im, a, b, c, d, wire) {
  const stride = 1 << (N_QUBITS - 1 - wire);
  const span = stride << 1;
  for (let block = 0; block < DIM; block += span) {
    for (let k = 0; k < stride; k++) {
      const lo = block + k;
      const hi = lo + stride;
      const lr = re[lo], li = im[lo];
      const hr = re[hi], hi_ = im[hi];
      re[lo] = a * lr + b * hr;
      im[lo] = a * li + b * hi_;
      re[hi] = c * lr + d * hr;
      im[hi] = c * li + d * hi_;
    }
  }
}

/** RY(theta) = [[cos(t/2), -sin(t/2)], [sin(t/2), cos(t/2)]] */
function applyRY(re, im, theta, wire) {
  const c = Math.cos(theta / 2);
  const s = Math.sin(theta / 2);
  applyReal2x2(re, im, c, -s, s, c, wire);
}

/** RZ(theta): diagonal, exp(-i t/2) on |0>, exp(+i t/2) on |1>. */
function applyRZ(re, im, theta, wire) {
  const half = theta / 2;
  const cs = Math.cos(half);
  const sn = Math.sin(half);
  const stride = 1 << (N_QUBITS - 1 - wire);
  const span = stride << 1;
  for (let block = 0; block < DIM; block += span) {
    for (let k = 0; k < stride; k++) {
      const lo = block + k;
      const hi = lo + stride;
      // |0> component: multiply by (cs - i*sn)
      const lr = re[lo], li = im[lo];
      re[lo] = lr * cs + li * sn;
      im[lo] = li * cs - lr * sn;
      // |1> component: multiply by (cs + i*sn)
      const hr = re[hi], hii = im[hi];
      re[hi] = hr * cs - hii * sn;
      im[hi] = hii * cs + hr * sn;
    }
  }
}

/** Rot(phi, theta, omega) decomposes to RZ(phi) then RY(theta) then RZ(omega). */
function applyRot(re, im, phi, theta, omega, wire) {
  applyRZ(re, im, phi, wire);
  applyRY(re, im, theta, wire);
  applyRZ(re, im, omega, wire);
}

function applyCNOT(re, im, control, target) {
  const cbit = 1 << (N_QUBITS - 1 - control);
  const tbit = 1 << (N_QUBITS - 1 - target);
  for (let i = 0; i < DIM; i++) {
    if ((i & cbit) !== 0 && (i & tbit) === 0) {
      const j = i | tbit;
      const tr = re[i], ti = im[i];
      re[i] = re[j]; im[i] = im[j];
      re[j] = tr; im[j] = ti;
    }
  }
}

/**
 * Expectation value of PauliZ on wire 0.
 * @param {number[][][]} weights shape [layers][14][3]
 * @param {number[]} x 14 features, each roughly 0..1
 * @returns {number} <Z_0> in [-1, 1]
 */
export function forward(weights, x) {
  const re = new Float64Array(DIM);
  const im = new Float64Array(DIM);
  re[0] = 1;

  for (let i = 0; i < N_QUBITS; i++) {
    applyRY(re, im, x[i] * Math.PI, i);
  }

  const layers = weights.length;
  for (let l = 0; l < layers; l++) {
    for (let i = 0; i < N_QUBITS; i++) {
      const w = weights[l][i];
      applyRot(re, im, w[0], w[1], w[2], i);
    }
    const r = l + 1;
    for (let i = 0; i < N_QUBITS; i++) {
      applyCNOT(re, im, i, (i + r) % N_QUBITS);
    }
  }

  // Wire 0 is the MSB, so its bit flips sign at the halfway point.
  const half = DIM >> 1;
  let sum = 0;
  for (let i = 0; i < DIM; i++) {
    const p = re[i] * re[i] + im[i] * im[i];
    sum += i < half ? p : -p;
  }
  return sum;
}

/**
 * d<Z_0>/dx by parameter shift.
 *
 * The embedding angle is theta_i = x_i * pi and RY is generated by Pauli-Y, so
 * df/dtheta = [f(theta + pi/2) - f(theta - pi/2)] / 2. Shifting x by 0.5 shifts
 * theta by pi/2, giving df/dx = (pi/2) * [f(x + 0.5) - f(x - 0.5)]. Exact, not
 * a finite-difference approximation.
 */
export function gradient(weights, x) {
  const g = new Array(N_QUBITS);
  for (let i = 0; i < N_QUBITS; i++) {
    const xp = x.slice();
    const xm = x.slice();
    xp[i] += 0.5;
    xm[i] -= 0.5;
    g[i] = (Math.PI / 2) * (forward(weights, xp) - forward(weights, xm));
  }
  return g;
}
